### ISSUE TITLE
Support encoding utf-8 character set

### ISSUE THREAD

**Issue by walkerrandolphsmith** [walkerrandolphsmith/encode-me#1]

**Comment by ChaudhariPrasad** [comment]
HI @walkerrandolphsmith,
Would like to work on this.

What exactly is the scenario and expectation out of this task.
Also can you help how i can create a demo using encode-me.

Thanks.
Prasad

**Comment by ChaudhariPrasad** [comment]
I have clone the repo now and able to open the index.html.
![image](https://cloud.githubusercontent.com/assets/17532347/19012307/e99e9a62-87ce-11e6-8874-1c84277134b4.png)
What are the next steps now.

**Comment by walkerrandolphsmith** [comment]
@ChaudhariPrasad thanks. I need to support taking a string like `≈Ω√ç` and getting a proper encoding like `4omIzqniiJrDpw==`. I will make the user interface. A unit test and a function would be great. Unit test is optional given there is nothing  in place to write one.
